import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.25rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans:    ["var(--font-sans)"],
        display: ["var(--font-display)"],
      },
      fontSize: {
        xs:    ["var(--text-xs)",   { lineHeight: "var(--leading-normal)" }],
        sm:    ["var(--text-sm)",   { lineHeight: "var(--leading-normal)" }],
        base:  ["var(--text-base)", { lineHeight: "var(--leading-normal)" }],
        lg:    ["var(--text-lg)",   { lineHeight: "var(--leading-snug)"   }],
        xl:    ["var(--text-xl)",   { lineHeight: "var(--leading-snug)"   }],
        "2xl": ["var(--text-2xl)",  { lineHeight: "var(--leading-snug)"   }],
        "3xl": ["var(--text-3xl)",  { lineHeight: "var(--leading-tight)"  }],
        "4xl": ["var(--text-4xl)",  { lineHeight: "var(--leading-tight)"  }],
        "5xl": ["var(--text-5xl)",  { lineHeight: "var(--leading-tight)"  }],
      },
      fontWeight: {
        regular:  "var(--weight-regular)",
        medium:   "var(--weight-medium)",
        semibold: "var(--weight-semibold)",
        bold:     "var(--weight-bold)",
      },
      letterSpacing: {
        tight:  "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide:   "var(--tracking-wide)",
      },
      colors: {
        // ---- 9-step neutral scale (use directly: bg-neutral-50, text-neutral-700, …) ----
        neutral: {
          0:   "hsl(var(--neutral-0)   / <alpha-value>)",
          50:  "hsl(var(--neutral-50)  / <alpha-value>)",
          100: "hsl(var(--neutral-100) / <alpha-value>)",
          200: "hsl(var(--neutral-200) / <alpha-value>)",
          300: "hsl(var(--neutral-300) / <alpha-value>)",
          400: "hsl(var(--neutral-400) / <alpha-value>)",
          500: "hsl(var(--neutral-500) / <alpha-value>)",
          700: "hsl(var(--neutral-700) / <alpha-value>)",
          900: "hsl(var(--neutral-900) / <alpha-value>)",
        },
        // ---- Brand cerulean with explicit interaction states ----
        brand: {
          DEFAULT: "hsl(var(--brand)         / <alpha-value>)",
          soft:    "hsl(var(--brand-soft)    / <alpha-value>)",
          subtle:  "hsl(var(--brand-subtle)  / <alpha-value>)",
          hover:   "hsl(var(--brand-hover)   / <alpha-value>)",
          active:  "hsl(var(--brand-active)  / <alpha-value>)",
          foreground: "hsl(var(--brand-fg)   / <alpha-value>)",
        },
        // ---- Semantic ----
        success: { DEFAULT: "hsl(var(--success) / <alpha-value>)", foreground: "hsl(var(--success-fg) / <alpha-value>)" },
        warning: { DEFAULT: "hsl(var(--warning) / <alpha-value>)", foreground: "hsl(var(--warning-fg) / <alpha-value>)" },
        danger:  { DEFAULT: "hsl(var(--danger)  / <alpha-value>)", foreground: "hsl(var(--danger-fg)  / <alpha-value>)" },

        // ---- Shadcn contract aliases (do not remove) ----
        border:     "hsl(var(--border) / <alpha-value>)",
        input:      "hsl(var(--input)  / <alpha-value>)",
        ring:       "hsl(var(--ring)   / <alpha-value>)",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        primary:    { DEFAULT: "hsl(var(--primary) / <alpha-value>)",    foreground: "hsl(var(--primary-foreground) / <alpha-value>)" },
        secondary:  { DEFAULT: "hsl(var(--secondary) / <alpha-value>)",  foreground: "hsl(var(--secondary-foreground) / <alpha-value>)" },
        muted:      { DEFAULT: "hsl(var(--muted) / <alpha-value>)",      foreground: "hsl(var(--muted-foreground) / <alpha-value>)" },
        accent:     { DEFAULT: "hsl(var(--accent) / <alpha-value>)",     foreground: "hsl(var(--accent-foreground) / <alpha-value>)" },
        destructive:{ DEFAULT: "hsl(var(--destructive) / <alpha-value>)",foreground: "hsl(var(--destructive-foreground) / <alpha-value>)" },
        popover:    { DEFAULT: "hsl(var(--popover) / <alpha-value>)",    foreground: "hsl(var(--popover-foreground) / <alpha-value>)" },
        card:       { DEFAULT: "hsl(var(--card) / <alpha-value>)",       foreground: "hsl(var(--card-foreground) / <alpha-value>)" },
        // Legacy gold alias kept so old markup doesn't crash; resolves to charcoal.
        gold:       { DEFAULT: "hsl(var(--neutral-900) / <alpha-value>)", foreground: "hsl(var(--neutral-0) / <alpha-value>)" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          primary: "hsl(var(--sidebar-primary) / <alpha-value>)",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          accent: "hsl(var(--sidebar-accent) / <alpha-value>)",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
        },
      },
      spacing: {
        1:  "var(--space-1)",
        2:  "var(--space-2)",
        3:  "var(--space-3)",
        4:  "var(--space-4)",
        5:  "var(--space-5)",
        6:  "var(--space-6)",
        8:  "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        24: "var(--space-24)",
      },
      borderRadius: {
        xs:    "var(--radius-xs)",
        sm:    "var(--radius-sm)",
        md:    "var(--radius-md)",
        lg:    "var(--radius-lg)",
        xl:    "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full:  "var(--radius-full)",
      },
      boxShadow: {
        xs:    "var(--shadow-xs)",
        sm:    "var(--shadow-sm)",
        md:    "var(--shadow-md)",
        lg:    "var(--shadow-lg)",
        xl:    "var(--shadow-xl)",
        focus: "var(--shadow-focus)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        emphasis: "var(--ease-emphasis)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        base: "var(--duration-base)",
        slow: "var(--duration-slow)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in":        { "0%": { opacity: "0", transform: "translateY(4px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "float":          { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 200ms var(--ease-standard)",
        "accordion-up":   "accordion-up 200ms var(--ease-standard)",
        "fade-in":        "fade-in 320ms var(--ease-emphasis)",
        "float":          "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
